# Keras Tutorial

In [1]:
import numpy as np
from random import randint
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

## Data Preparation and Preprocessing 

In [2]:
train_labels = []
train_samples = []

In [3]:
for i in range(50):
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)
    
for i in range(1000):
    random_younger = randint(13,64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    random_older = randint(65,100)
    train_samples.append(random_older)
    train_labels.append(0)

In [4]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels, train_samples = shuffle(train_labels, train_samples)

In [5]:
print(train_samples)

[92 64 95 ... 76 73 32]


In [6]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [7]:
print(scaled_train_samples)

[[0.90804598]
 [0.5862069 ]
 [0.94252874]
 ...
 [0.72413793]
 [0.68965517]
 [0.2183908 ]]


## Simple tf.keras Sequential Model

In [8]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [9]:
physial_devices = tf.config.experimental.list_physical_devices('GPU')
print("Avaialble: ", len(physial_devices))


Avaialble:  0


In [10]:
model = Sequential([
    Dense(units=16, input_shape=(1,), activation='relu'), # irst hidden layer - 16 neurons
    Dense(units=32, activation='relu'),
    Dense(units=2, activation='softmax')
])

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [13]:
model.fit(x=scaled_train_samples, y=train_labels, validation_split=0.1, batch_size=10, epochs=30, shuffle=True, verbose=2)

Epoch 1/30
189/189 - 0s - loss: 0.6704 - accuracy: 0.5386 - val_loss: 0.6551 - val_accuracy: 0.5762
Epoch 2/30
189/189 - 0s - loss: 0.6341 - accuracy: 0.6471 - val_loss: 0.6200 - val_accuracy: 0.6333
Epoch 3/30
189/189 - 0s - loss: 0.5934 - accuracy: 0.7058 - val_loss: 0.5799 - val_accuracy: 0.7238
Epoch 4/30
189/189 - 0s - loss: 0.5545 - accuracy: 0.7667 - val_loss: 0.5448 - val_accuracy: 0.7381
Epoch 5/30
189/189 - 0s - loss: 0.5134 - accuracy: 0.8196 - val_loss: 0.5025 - val_accuracy: 0.7810
Epoch 6/30
189/189 - 0s - loss: 0.4686 - accuracy: 0.8508 - val_loss: 0.4588 - val_accuracy: 0.8286
Epoch 7/30
189/189 - 0s - loss: 0.4203 - accuracy: 0.8878 - val_loss: 0.4120 - val_accuracy: 0.8619
Epoch 8/30
189/189 - 0s - loss: 0.3741 - accuracy: 0.9063 - val_loss: 0.3689 - val_accuracy: 0.8952
Epoch 9/30
189/189 - 0s - loss: 0.3329 - accuracy: 0.9259 - val_loss: 0.3322 - val_accuracy: 0.9048
Epoch 10/30
189/189 - 0s - loss: 0.2969 - accuracy: 0.9360 - val_loss: 0.2987 - val_accuracy: 0.9190

## Process Test Data

In [25]:
test_labels = []
test_samples = []

In [26]:
for i in range(10):
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)
    
for i in range(200):
    random_younger = randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    random_older = randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)

In [27]:
test_labels = np.array(test_labels)
test_samples = np.array(test_samples)
test_labels, test_samples = shuffle(test_labels, test_samples)

In [33]:
# print(test_samples)

In [29]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))

In [32]:
# print(scaled_test_samples)

## Predict

In [34]:
prediction = model.predict(x=scaled_test_samples, batch_size=10, verbose=0)

In [40]:
print(prediction[:10])

[[0.0135096  0.98649037]
 [0.5729432  0.42705682]
 [0.2973276  0.7026724 ]
 [0.11774272 0.8822573 ]
 [0.0036547  0.99634534]
 [0.09580184 0.90419817]
 [0.62823546 0.37176454]
 [0.9553528  0.04464718]
 [0.00454504 0.9954549 ]
 [0.7283415  0.2716585 ]]


In [37]:
rounded_prediction = np.argmax(prediction, axis=-1)

In [42]:
print(rounded_prediction[:10])

[1 0 1 1 1 1 0 0 1 0]


In [43]:
from tensorflow import lite

In [44]:
converter = lite.TFLiteConverter.from_keras_model(model)
tfmodel = converter.convert()
open("linear.tflite", "wb").write(tfmodel)

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: C:\Users\KAVINDA\AppData\Local\Temp\tmp2lchde9u\assets


4248

# Using BLE RSSI Values to Classify Proximity with Deep Neural Networks